# Header
menu:
  主页: /
  所有文章: /archives
  TAG: /tag
  合集: /category
  # 关于我: /about

# SubNav
subnav:
  #github: "https://github.com/yourname"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "example@example.com"
  #facebook: "#"
  #twitter: "#"
  #linkedin: "#"

# rss: /atom.xml

# Content
excerpt_link: 全文
fancybox: true
mathjax: true

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
# google_analytics: ''
# favicon: /favicon.png

#你的头像url
avatar: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1595309120659&di=8b737637cbd3d9ac674aeb410c7e6ac9&imgtype=0&src=http%3A%2F%2Fd.ifengimg.com%2Fmw600%2Fimg1.ugc.ifeng.com%2Fnewugc%2F20171128%2F10%2Fwemedia%2Ff713471abdc51030ff0d818414a7de925b687e7e_size1260_w1280_h1920.jpg
#是否开启分享
share: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends: true
#####  奥巴马的博客: http://localhost:4000/
#####  卡卡的美丽传说: http://localhost:4000/
#####  本泽马的博客: http://localhost:4000/
#####  吉格斯的博客: http://localhost:4000/
#####  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 随便写点 ...
